//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/battle.proto
namespace battle_msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"vector")]
  public partial class vector : global::ProtoBuf.IExtensible
  {
    public vector() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"entity_info")]
  public partial class entity_info : global::ProtoBuf.IExtensible
  {
    public entity_info() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _type_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type_id
    {
      get { return _type_id; }
      set { _type_id = value; }
    }
    private int _camp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"camp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int camp
    {
      get { return _camp; }
      set { _camp = value; }
    }
    private int _blood;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"blood", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int blood
    {
      get { return _blood; }
      set { _blood = value; }
    }
    private float _cd;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"cd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float cd
    {
      get { return _cd; }
      set { _cd = value; }
    }
    private int _row;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"row", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int row
    {
      get { return _row; }
      set { _row = value; }
    }
    private int _col;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"col", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int col
    {
      get { return _col; }
      set { _col = value; }
    }
    private battle_msg.vector _pos;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public battle_msg.vector pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"bullet_info")]
  public partial class bullet_info : global::ProtoBuf.IExtensible
  {
    public bullet_info() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _type_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type_id
    {
      get { return _type_id; }
      set { _type_id = value; }
    }
    private int _camp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"camp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int camp
    {
      get { return _camp; }
      set { _camp = value; }
    }
    private int _damage;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int damage
    {
      get { return _damage; }
      set { _damage = value; }
    }
    private int _path;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"path", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int path
    {
      get { return _path; }
      set { _path = value; }
    }
    private battle_msg.vector _begin_pos;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"begin_pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public battle_msg.vector begin_pos
    {
      get { return _begin_pos; }
      set { _begin_pos = value; }
    }
    private battle_msg.vector _pos;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public battle_msg.vector pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private battle_msg.vector _begin_speed;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"begin_speed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public battle_msg.vector begin_speed
    {
      get { return _begin_speed; }
      set { _begin_speed = value; }
    }
    private battle_msg.vector _speed;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public battle_msg.vector speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private double _begin_time;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"begin_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double begin_time
    {
      get { return _begin_time; }
      set { _begin_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"room_info")]
  public partial class room_info : global::ProtoBuf.IExtensible
  {
    public room_info() {}
    
    private int _state;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private double _begin_time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"begin_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double begin_time
    {
      get { return _begin_time; }
      set { _begin_time = value; }
    }
    private double _now_time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"now_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double now_time
    {
      get { return _now_time; }
      set { _now_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"update_state")]
  public partial class update_state : global::ProtoBuf.IExtensible
  {
    public update_state() {}
    
    private int _state;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private int _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private float _p1 = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"p1", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float p1
    {
      get { return _p1; }
      set { _p1 = value; }
    }
    private float _p2 = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"p2", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float p2
    {
      get { return _p2; }
      set { _p2 = value; }
    }
    private float _p3 = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"p3", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float p3
    {
      get { return _p3; }
      set { _p3 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c_login_hall")]
  public partial class c_login_hall : global::ProtoBuf.IExtensible
  {
    public c_login_hall() {}
    
    private long _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s_login_hall")]
  public partial class s_login_hall : global::ProtoBuf.IExtensible
  {
    public s_login_hall() {}
    
    private string _res;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"res", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string res
    {
      get { return _res; }
      set { _res = value; }
    }
    private long _uid = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _icon = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c_login")]
  public partial class c_login : global::ProtoBuf.IExtensible
  {
    public c_login() {}
    
    private long _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s_login")]
  public partial class s_login : global::ProtoBuf.IExtensible
  {
    public s_login() {}
    
    private string _res;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"res", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string res
    {
      get { return _res; }
      set { _res = value; }
    }
    private long _uid = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _icon = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private int _camp = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"camp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int camp
    {
      get { return _camp; }
      set { _camp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c_get_room_info")]
  public partial class c_get_room_info : global::ProtoBuf.IExtensible
  {
    public c_get_room_info() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s_get_room_info")]
  public partial class s_get_room_info : global::ProtoBuf.IExtensible
  {
    public s_get_room_info() {}
    
    private string _res;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"res", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string res
    {
      get { return _res; }
      set { _res = value; }
    }
    private battle_msg.room_info _info;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public battle_msg.room_info info
    {
      get { return _info; }
      set { _info = value; }
    }
    private readonly global::System.Collections.Generic.List<battle_msg.entity_info> _entitys = new global::System.Collections.Generic.List<battle_msg.entity_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"entitys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<battle_msg.entity_info> entitys
    {
      get { return _entitys; }
    }
  
    private readonly global::System.Collections.Generic.List<battle_msg.bullet_info> _bullets = new global::System.Collections.Generic.List<battle_msg.bullet_info>();
    [global::ProtoBuf.ProtoMember(4, Name=@"bullets", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<battle_msg.bullet_info> bullets
    {
      get { return _bullets; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c_create_entity")]
  public partial class c_create_entity : global::ProtoBuf.IExtensible
  {
    public c_create_entity() {}
    
    private int _type_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type_id
    {
      get { return _type_id; }
      set { _type_id = value; }
    }
    private int _row;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"row", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int row
    {
      get { return _row; }
      set { _row = value; }
    }
    private int _col;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"col", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int col
    {
      get { return _col; }
      set { _col = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s_room_state")]
  public partial class s_room_state : global::ProtoBuf.IExtensible
  {
    public s_room_state() {}
    
    private battle_msg.room_info _info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public battle_msg.room_info info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s_create_entity")]
  public partial class s_create_entity : global::ProtoBuf.IExtensible
  {
    public s_create_entity() {}
    
    private battle_msg.entity_info _einfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"einfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public battle_msg.entity_info einfo
    {
      get { return _einfo; }
      set { _einfo = value; }
    }
    private int _use_gold;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"use_gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int use_gold
    {
      get { return _use_gold; }
      set { _use_gold = value; }
    }
    private int _cur_gold;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"cur_gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cur_gold
    {
      get { return _cur_gold; }
      set { _cur_gold = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s_destroy_entity")]
  public partial class s_destroy_entity : global::ProtoBuf.IExtensible
  {
    public s_destroy_entity() {}
    
    private int _eid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"eid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int eid
    {
      get { return _eid; }
      set { _eid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s_fire")]
  public partial class s_fire : global::ProtoBuf.IExtensible
  {
    public s_fire() {}
    
    private int _eid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"eid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int eid
    {
      get { return _eid; }
      set { _eid = value; }
    }
    private battle_msg.bullet_info _binfo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"binfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public battle_msg.bullet_info binfo
    {
      get { return _binfo; }
      set { _binfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s_collision")]
  public partial class s_collision : global::ProtoBuf.IExtensible
  {
    public s_collision() {}
    
    private battle_msg.entity_info _einfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"einfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public battle_msg.entity_info einfo
    {
      get { return _einfo; }
      set { _einfo = value; }
    }
    private battle_msg.bullet_info _binfo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"binfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public battle_msg.bullet_info binfo
    {
      get { return _binfo; }
      set { _binfo = value; }
    }
    private bool _bullet_destroy;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"bullet_destroy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool bullet_destroy
    {
      get { return _bullet_destroy; }
      set { _bullet_destroy = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s_update_state")]
  public partial class s_update_state : global::ProtoBuf.IExtensible
  {
    public s_update_state() {}
    
    private readonly global::System.Collections.Generic.List<battle_msg.update_state> _states = new global::System.Collections.Generic.List<battle_msg.update_state>();
    [global::ProtoBuf.ProtoMember(1, Name=@"states", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<battle_msg.update_state> states
    {
      get { return _states; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}